import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

public class Main {

    public static void main(String[] args) {

        Musician arethaFranklin = new Vocalist("Aretha", "Franklin", "USA",
                "R&B Soul", "1960s - 2018",
                "Billie Holiday");
        Song think = new Song("Think", arethaFranklin,
                "Jams", "https://youtu.be/HqYnevHibaI");

        Musician jillScott = new Vocalist("Jill", "Scott", "USA",
                "R&B Soul", "2000s - present",
                "Erykah Badu");
        Song soInLove = new Song("So In Love", jillScott,
                "Jams", "https://youtu.be/V1OC_XmeIck");

        Musician milesDavis = new TrumpetPlayer("Miles", "Davis", "USA",
                "Jazz", "1940s - 1990s",
                "B Flat");
        Song soWhat = new Song("So What", milesDavis,
                "Jams", "https://youtu.be/zqNTltOGh5c");

        Musician louisArmstrong = new TrumpetPlayer("Louis", "Armstrong", "USA",
                "Jazz", "1910s - 1970s",
                "B Flat");
        Song hotterThanThat = new Song("Hotter Than That", louisArmstrong,
                "Jams", "https://youtu.be/tAlrpx40UnE");

        Musician carlosSantana = new Guitarist("Carlos", "Santana", "USA",
                "Latin Rock", "1960s - present",
                6);
        Song smooth = new Song("Smooth", carlosSantana,
                "Jams", "https://youtu.be/6Whgn_iE5uc");

        Musician prince = new Guitarist("Prince", "" ,"USA",
                "Funk Rock", "1970s - 2016",
                6);
        Song purpleRain = new Song("Purple Rain", prince,
                "Jams", "https://youtu.be/TvnYmWpD_T8");


        // Adding songs together in a playlist
        ArrayList<Song> jams = new ArrayList<>();
        jams.add(think);
        jams.add(soInLove);
        jams.add(soWhat);
        jams.add(hotterThanThat);
        jams.add(smooth);
        jams.add(purpleRain);

        for (Song song : jams) {
            song.show();
            System.out.println();

        }

        // way to write the musicians in a song's playlist to disk
        try {
            PrintWriter pw = new PrintWriter("myjams.txt");
            for (Song jam : jams) {
                pw.println(jam.musician.firstName + " " + jam.musician.lastName);
            }
            pw.close();
        } catch (Exception ex) {
            System.err.println("Could not write the song info.");
        }

        // way to read contents of a file and display to console
        try {
            FileReader fileReader = new FileReader("myjams.txt");
            int data = fileReader.read();
            while(data != - 1) {
                System.out.print((char)data);
                data = fileReader.read();
            }
            fileReader.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace(); // added by me as not auto-generated by IntelliJ
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
